In [1]:
import numpy as np

In [38]:
psis = np.zeros(9)
for ii in range(9):
    psis[ii] = ii + 1
psis = psis.reshape((3, 3))

In [39]:
psis

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [34]:
deriv = np.zeros((3, 3))

In [35]:
deriv[2][2] = deriv[1][1] = deriv[0][0] = -2

In [36]:
deriv

array([[-2.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.]])

In [37]:
deriv[1][0] = deriv[2][1] = 1

In [15]:
deriv[0][1] = deriv[1][2] = 1

In [16]:
deriv

array([[-2.,  1.,  0.],
       [ 1., -2.,  1.],
       [ 0.,  1., -2.]])

In [40]:
np.kron(deriv, psis)

array([[ -2.,  -4.,  -6.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ -8., -10., -12.,   0.,   0.,   0.,   0.,   0.,   0.],
       [-14., -16., -18.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  1.,   2.,   3.,  -2.,  -4.,  -6.,   0.,   0.,   0.],
       [  4.,   5.,   6.,  -8., -10., -12.,   0.,   0.,   0.],
       [  7.,   8.,   9., -14., -16., -18.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   1.,   2.,   3.,  -2.,  -4.,  -6.],
       [  0.,   0.,   0.,   4.,   5.,   6.,  -8., -10., -12.],
       [  0.,   0.,   0.,   7.,   8.,   9., -14., -16., -18.]])

In [62]:
I = np.flipud(np.identity(3)) + np.identity(3).T

In [63]:
I[1][1] = 1

In [64]:
I

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [67]:
np.kron(deriv, np.identity(3))

array([[-2., -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -2., -0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0., -2., -0., -0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0., -2., -0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -0., -0., -2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0., -2., -0., -0.],
       [ 0.,  0.,  0.,  0.,  1.,  0., -0., -2., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -0., -0., -2.]])

In [70]:
D = np.identity(3) * 2

In [71]:
D

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [77]:
np.kron(np.identity(3), psis) 

array([[1., 2., 3., 0., 0., 0., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0., 0., 0., 0.],
       [7., 8., 9., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0.],
       [0., 0., 0., 4., 5., 6., 0., 0., 0.],
       [0., 0., 0., 7., 8., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3.],
       [0., 0., 0., 0., 0., 0., 4., 5., 6.],
       [0., 0., 0., 0., 0., 0., 7., 8., 9.]])

In [78]:
np.kron(psis, np.identity(3)) 

array([[1., 0., 0., 2., 0., 0., 3., 0., 0.],
       [0., 1., 0., 0., 2., 0., 0., 3., 0.],
       [0., 0., 1., 0., 0., 2., 0., 0., 3.],
       [4., 0., 0., 5., 0., 0., 6., 0., 0.],
       [0., 4., 0., 0., 5., 0., 0., 6., 0.],
       [0., 0., 4., 0., 0., 5., 0., 0., 6.],
       [7., 0., 0., 8., 0., 0., 9., 0., 0.],
       [0., 7., 0., 0., 8., 0., 0., 9., 0.],
       [0., 0., 7., 0., 0., 8., 0., 0., 9.]])

In [79]:
psis

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [128]:
potentials = np.identity(9) * psis.ravel()

In [129]:
potentials

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]])