In [1]:
import numpy as np

In [2]:
test = np.zeros((3, 3))

In [3]:
for ii in range(3):
    for jj in range(3): 
        test[ii][jj] = (ii + 1) * (jj + 1 + ii)

In [4]:
test

array([[ 1.,  2.,  3.],
       [ 4.,  6.,  8.],
       [ 9., 12., 15.]])

In [5]:
test.reshape((1, 9))

array([[ 1.,  2.,  3.,  4.,  6.,  8.,  9., 12., 15.]])

In [13]:
test.ravel() * np.identity(9)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 12.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 15.]])